name: Docker Image CI

on:
  push:
    branches: [ "main_v2" ]
  pull_request:
    branches: [ "main_v2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:  # 👈 Add this to grant GITHUB_TOKEN rights for packages
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/hardikhari96/kubectl/haripatel-dev-v2
        tags: |
          type=ref,event=branch
          type=sha
        labels: |
          org.opencontainers.image.source=${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
